development:
  adapter: postgresql
  encoding: utf8
  database: andtohold_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: andtohold_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: andtohold_production
  pool: 5
  username: 
  password: